name: Build

on:
  workflow_dispatch: # 이 부분이 수동 실행을 가능하게 합니다.
    inputs: # (선택 사항) 수동 실행 시 입력 받을 파라미터 정의
      environment:
        description: '배포 환경'
        required: false
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install deps
        run: npm install
